(()=>{'use strict';
 const main=document.querySelector('[data-commerce-channel]');if(!main)return;
 const key=main.dataset.commerceChannel||new URLSearchParams(location.search).get('platform');
 const platform=(window.AIRIS_PLATFORMS||[]).find(p=>p.key===key),detail=window.AIRIS_CHANNEL_DETAILS?.[key];
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 if(!platform||!detail){document.title='选择内容频道 · 艾瑞斯';main.innerHTML='<section class="wrap channel-not-found"><h1>请选择你想看的内容</h1><p>这个频道地址暂时无法识别，从下方平台入口继续。</p><div class="channel-directory">'+(window.AIRIS_PLATFORMS||[]).map(p=>`<a class="button" href="${esc(p.url)}">${esc(p.label)}</a>`).join('')+'</div></section>';return}
 document.title=platform.label+' · AI 电商经营内容 · 艾瑞斯 AIRIS';document.querySelector('meta[name=description]')?.setAttribute('content',detail.description);
 main.dataset.catalog='collection';main.dataset.fixedCategory=platform.category;main.dataset.platformKey=key;
 const refs=window.AIRIS_PLATFORM_REFERENCES?.[platform.category]||[];
 main.innerHTML=`<section class="wrap collection-intro"><div><p class="section-note">艾瑞斯 / ${esc(platform.label)}${key==='international'?'专区':'内容'}</p><h1>${esc(detail.title).replace('\n','<br>')}</h1><p class="collection-deck">${esc(detail.description)}</p><div class="collection-scope">${detail.topics.map(x=>`<span>${esc(x)}</span>`).join('')}</div></div><aside class="collection-editor-note"><span>把资料读明白，把方法用起来。</span><p>文章附上参考出处和具体步骤。先选眼前的问题，再跟着清单做一次。</p><a href="#channel-reading">开始阅读 <span aria-hidden="true">↓</span></a></aside></section>
 <div class="wrap collection-layout" id="channel-reading"><section class="catalog-section"><div class="collection-list-heading"><h2>${esc(platform.label)}，从这里开始读</h2><span data-result-count role="status">正在读取内容…</span></div><div class="catalog-tools"><div class="filter-tabs" role="group" aria-label="内容范围"><button type="button" class="filter-tab active" data-category="${esc(platform.category)}" aria-pressed="true">全部内容</button></div><form class="catalog-search" role="search"><label class="sr-only" for="catalog-query">搜索${esc(platform.label)}内容</label><input id="catalog-query" name="q" type="search" maxlength="100" placeholder="在本频道搜索问题"><button type="submit" aria-label="搜索">⌕</button></form></div><div class="catalog-grid" data-catalog-list aria-live="polite" aria-busy="true"><div class="loading-state">正在读取已发布内容…</div></div><nav class="pagination" data-pagination aria-label="内容分页"></nav></section>
 <aside class="collection-rail"><section class="collection-template"><small>看完，拿一份清单试试</small><h2>${esc(detail.templateName)}</h2><p>${esc(detail.templateDescription)}</p><a href="${esc(detail.template)}" download>下载可编辑清单 <span aria-hidden="true">↓</span></a><span class="template-format">Markdown 文字格式</span></section><section class="collection-course" hidden data-channel-course></section><section class="collection-references" id="channel-references"><small>阅读原始资料</small><h2>官方资料，从这里核对</h2>${refs.length?refs.slice(0,4).map(r=>`<a href="${esc(r.url)}" target="_blank" rel="noopener noreferrer"><strong>${esc(r.title)}</strong><span>${esc(r.publisher)} · ${esc(r.checked)} 查阅 ↗</span></a>`).join(''):'<p>相关文章正文末尾提供参考原文。</p>'}</section><section class="collection-return"><h2>换个方向，继续看看。</h2><p>平台不同，经营问题也有相通之处。</p><a href="intelligence.html">浏览全部行业内容 ↗</a></section></aside></div>`;
 if(detail.course){const panel=main.querySelector('[data-channel-course]');(async()=>{try{const item=location.protocol==='file:'?(window.AIRIS_GUIDES||[]).find(x=>x.id===detail.course):await window.AIRIS_CONTENT.fetch('/api/public/content/'+encodeURIComponent(detail.course)).then(r=>{if(!r.ok)throw Error();return r.json()});if(!item||item.type!=='course')return;panel.innerHTML=`<small>沿着章节，学得更完整</small><h2>${esc(item.title)}</h2><p>${esc(item.summary.replace(/^文字课[｜|]\s*/,''))}</p><a href="content.html?id=${encodeURIComponent(item.id)}">阅读 ${item.chapters?.length||0} 节文字课 ↗</a>`;panel.hidden=false}catch{panel.hidden=true}})();}
})();
