const quiz=document.querySelector('#quiz');
const questions=[
{title:'你平时主要做什么？',desc:'选一个最接近你的身份就好。',options:[['operator','01','电商运营 / 营销从业者','关注新趋势、工具与专业成长'],['owner','02','品牌经营者 / 企业负责人','关注团队能力与企业增长'],['crossborder','03','跨境卖家 / 出海团队','关注全球市场与本地经营']]},
{title:'你现在最关心什么？',desc:'先选一个想了解的方向。',options:[['insights','↗','最近发生了什么新变化','看平台消息、跨境市场和 AI 变化'],['tools','⌁','哪些 AI 工具值得试','找到适合业务的工具和使用路径'],['team','◎','我和团队该怎么学','找课程、看资料、参加交流']]},
{title:'你希望怎样开始？',desc:'按你的节奏，选择下一步。',options:[['read','01','先逛逛，看点内容','看资讯、指南和工具介绍'],['learn','02','找课程，认真学一学','了解课程与行业活动'],['talk','03','把我的问题说一说','让 AI 业务合伙人了解需求']]}
];
let step=0,answers=[null,null,null];
if(new URLSearchParams(location.search).get('goal')==='team'){answers[0]='owner';answers[1]='team';}
let pathResult=null;
function renderQuiz(){if(step===3){renderResult();return;}const q=questions[step];quiz.innerHTML=`<div class="h5-meter" aria-label="第 ${step+1} 步，共 3 步">${questions.map((_,i)=>`<span class="${i<=step?'done':''}"></span>`).join('')}</div><div class="h5-question"><div class="eyebrow">YOUR NEXT MOVE / 0${step+1}</div><h2>${q.title}</h2><p>${q.desc}</p><div class="h5-options" role="group" aria-label="${q.title}">${q.options.map(([id,symbol,label,desc])=>`<button class="h5-option" data-option="${id}" aria-pressed="${answers[step]===id}"><span class="option-symbol">${symbol}</span><span><strong>${label}</strong><small>${desc}</small></span><span class="radio" aria-hidden="true"></span></button>`).join('')}</div><div class="h5-error" role="alert" id="quiz-error"></div><div class="h5-controls">${step?'<button class="prev" data-quiz="prev">← 上一步</button>':''}<button class="btn btn-primary next" data-quiz="next">${step===2?'发现我的下一步':'下一步'} →</button></div><p class="h5-disclaimer">3 个问题 · 不收集联系方式<br>按兴趣推荐资源，可随时重新选择。</p></div>`;}
function getRecommendation(){const [role,interest,mode]=answers;const base={
insights:{title:role==='crossborder'?'先看和你的市场有关的消息。':'先逛情报中心，找和你有关的变化。',tag:'AIRIS INTELLIGENCE',intro:'平台改了什么、AI 又能做什么，先看原始消息和编辑解读。',href:'intelligence.html',label:'进入情报中心',steps:[['看一篇行业内容','从你关注的平台或市场开始，查看消息来源、发布时间和适用范围。'],['找到关注主题','结合你的市场、平台与经营阶段，梳理长期需要跟踪的问题。'],['把问题带入交流','让 AI 业务合伙人推荐下一篇文章、一个方法或学习入口。']]},
tools:{title:'先找一个好用的工具。',tag:'AIRIS TOOLKIT',intro:'说清楚想解决什么问题，再看工具能帮你做哪一步、上手要花多少时间。',href:'toolkit.html',label:'浏览工具与方法',steps:[['明确应用场景','从获客、内容、客户服务或团队协作中的具体问题出发。'],['比较使用条件','关注输入材料、质量要求、使用成本与团队学习门槛。'],['建立自己的方法库','保存适用模板与经验，逐步形成可复用的应用方法。']]},
team:{title:role==='owner'?'先找一堂适合团队的课。':'从一个想学会的问题开始。',tag:'AIRIS ACADEMY & ENTERPRISE',intro:'浏览课程介绍、培训视频与学习资料，先挑和当前工作最有关的内容。',href:'academy.html',label:'进入 AI 商学院',steps:[['确定能力重点','先看业务目标与岗位能力缺口，明确学习应服务的方向。'],['匹配学习与专家','从课程、公开交流或企业沟通中选择适合的支持方式。'],['回到经营现场','结合真实场景验证方法，并持续复盘团队的应用能力。']]}
}[interest];if(mode==='talk'){base.href='partner.html';base.label='与 AI 业务合伙人对话';base.start='建议下一步：说出你的平台、业务阶段与当前问题。';}else if(mode==='learn'){base.href='academy.html';base.label='探索 AI 商学院';base.start='建议下一步：查看课程介绍与已发布视频，选择你最想学会的内容。';}else{base.start='建议下一步：先看一篇内容，觉得有用再继续深入。';}return base;}
function renderResult(){pathResult=getRecommendation();quiz.innerHTML=`<div class="h5-result"><div class="eyebrow">YOUR NEXT MOVE</div><div class="result-card"><span class="small mono">${pathResult.tag}</span><h2>${pathResult.title}</h2><p>${pathResult.intro}</p></div><p class="small muted">${pathResult.start}</p><ol class="result-roadmap">${pathResult.steps.map(([title,desc])=>`<li><strong>${title}</strong><small>${desc}</small></li>`).join('')}</ol><div class="actions"><a class="btn btn-primary" href="${pathResult.href}">${pathResult.label} ↗</a><a class="btn btn-soft" href="partner.html">让 AI 业务合伙人继续推荐 ↗</a><button class="btn btn-soft" data-quiz="download">保存我的探索路径 ↓</button></div><button class="restart" data-quiz="restart">重新选择</button><p class="h5-disclaimer">根据本次选择推荐浏览入口；具体课程与活动安排以对应栏目为准。</p></div>`;}
document.addEventListener('click',e=>{const el=e.target.closest('button');if(!el)return;if(el.dataset.option){answers[step]=el.dataset.option;document.querySelectorAll('[data-option]').forEach(b=>b.setAttribute('aria-pressed',b===el));document.querySelector('#quiz-error').textContent='';return;}switch(el.dataset.quiz){case'next':if(!answers[step]){document.querySelector('#quiz-error').textContent='请先选择一个最贴近你情况的选项。';return;}step++;renderQuiz();break;case'prev':step--;renderQuiz();break;case'restart':step=0;answers=[null,null,null];renderQuiz();break;case'download':{const text=`# 艾瑞斯 · 我的探索路径\n\n${pathResult.title}\n\n${pathResult.intro}\n\n${pathResult.start}\n\n${pathResult.steps.map(([t,d],i)=>`${i+1}. ${t}：${d}`).join('\n')}\n\n选择记录：${questions.map((q,i)=>q.options.find(o=>o[0]===answers[i])[2]).join(' / ')}\n\n本建议来自三项兴趣选择。\n`;const a=document.createElement('a'),url=URL.createObjectURL(new Blob([text],{type:'text/markdown;charset=utf-8'}));a.href=url;a.download='AIRIS-my-discovery-path.md';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('已生成可保存的探索路径。');break;}}});renderQuiz();
