const $ = selector => document.querySelector(selector);
const escapeHTML = value => String(value ?? '').replace(/[&<>"']/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const stateKey = 'airis-member-desk-v2';
const blankState = () => ({read:[],saved:[],notes:[]});
let member = blankState();
try { const stored = JSON.parse(localStorage.getItem(stateKey) || 'null'); if (stored && typeof stored === 'object') member = {read:Array.isArray(stored.read)?stored.read:[],saved:Array.isArray(stored.saved)?stored.saved.filter(id=>typeof id==='string'):[],notes:Array.isArray(stored.notes)?stored.notes.filter(n=>n&&typeof n.title==='string'&&typeof n.body==='string'):[]}; } catch {}
function save() { try {localStorage.setItem(stateKey,JSON.stringify(member));return true;} catch {toast('本次更改保留在页面内；浏览器暂不允许本机保存。');return false;} }
const guides = [
 {id:'start',type:'入门',title:'AI 工具这么多，先学哪一个？',description:'先选一个常见问题，再挑一类工具，学习才不会被工具名单淹没。',label:'找到起点',steps:['写下最近反复做的一件事，例如整理资料、回复常见问题、理解一份报表。','用同一份不含客户隐私的示例材料试用候选工具，比较结果是否准确、是否方便修改。','记录节省了哪些步骤、还需要你判断什么，再决定是否深入学习。'],prompt:'我最想减少的重复工作是什么？试过后，哪些地方仍需要人工判断？',href:'toolkit.html',link:'按场景找工具'},
 {id:'team',type:'团队',title:'老板想上 AI，团队应该先做什么？',description:'先对齐一个小目标，再决定学什么、由谁试、如何看结果。',label:'团队共学',steps:['选一个团队普遍遇到的问题，并约定怎样判断“有帮助”，不要只看生成数量。','让业务负责人和实际使用者一起试用，记录输入材料、修改过程和质量问题。','把有效方法整理成共享笔记，再安排培训、权限和复盘节奏。'],prompt:'团队最需要解决的一个问题是什么？谁最了解现有做法？',href:'enterprise.html',link:'了解企业合作'},
 {id:'global',type:'跨境',title:'跨境消息很多，怎么判断和我有关？',description:'把平台、市场、发布时间和原始来源看清楚，再决定要不要行动。',label:'跨境观察',steps:['先确认消息涉及的平台、站点、适用对象和生效时间，避免把其他市场的规则套过来。','找到平台公告等原始来源，区分已生效的规定、测试功能和个人判断。','记下对当前经营的可能影响与待确认问题，再带到课程或交流中讨论。'],prompt:'我关注哪个市场与平台？这条变化影响我的哪个环节？',href:'intelligence.html',link:'查看行业情报'}
];
const destinations = [
 {id:'intelligence',label:'情报中心',description:'看平台、AI 与跨境市场的新变化。',href:'intelligence.html',code:'01 / READ'},
 {id:'toolkit',label:'能力中心',description:'按业务场景挑工具、找方法。',href:'toolkit.html',code:'02 / EXPLORE'},
 {id:'academy',label:'AI 商学院',description:'浏览课程、培训视频和学习资料。',href:'academy.html',code:'03 / LEARN'},
 {id:'events',label:'产业活动',description:'查找行业交流与活动内容。',href:'events.html',code:'04 / MEET'},
 {id:'enterprise',label:'企业合作',description:'了解团队培训和落地支持。',href:'enterprise.html',code:'05 / CONNECT'},
 {id:'partner',label:'AI 业务合伙人',description:'说出问题，找到合适的下一步。',href:'partner.html',code:'06 / ASK'}
];
const pageNames = {home:'我的发现',courses:'入门阅读',notes:'学习笔记',resources:'方法与资源',saved:'我的收藏'};
const aliases = {projects:'notes',assets:'resources',reviews:'saved'};
let filter = '全部', query = '';
const dialog = $('#lab-dialog');
const closeDialog = () => dialog.close();
$('.close-dialog').addEventListener('click',closeDialog);
dialog.addEventListener('click',event=>{if(event.target===dialog){const r=dialog.getBoundingClientRect();if(event.clientX<r.left||event.clientX>r.right||event.clientY<r.top||event.clientY>r.bottom)closeDialog();}});
function openDialog(title,html){$('#dialog-heading').textContent=title;$('#dialog-content').innerHTML=html;dialog.showModal();}
function heading(title,description,action=''){return `<div class="workspace-title"><div><h1>${title}</h1><p>${description}</p></div>${action}</div>`;}
function render(){const hash=location.hash.slice(1)||'home';const route=aliases[hash]||hash;const current=pageNames[route]?route:'home';document.querySelectorAll('[data-page]').forEach(link=>{const active=link.dataset.page===current;link.classList.toggle('active',active);active?link.setAttribute('aria-current','page'):link.removeAttribute('aria-current');});$('#breadcrumb').textContent=`我的艾瑞斯 / ${pageNames[current]}`;({home:renderHome,courses:renderCourses,notes:renderNotes,resources:renderResources,saved:renderSaved}[current])();}
function renderHome(){const count=guides.filter(g=>member.read.includes(g.id)).length;$('#workspace').innerHTML=`${heading('今天，想先了解什么？','看看新变化，学一点方法，把有用的内容留给自己。','<a class="btn btn-primary" href="h5.html">帮我找个起点 ↗</a>')}<section class="work-banner"><div><div class="eyebrow" style="color:var(--lime)">MY AIRIS / LEARN & EXPLORE</div><h2>让 AI 成为<br>你的生意优势。</h2><p>从一条情报、一段课程、一次交流开始。<br>不用一次学完所有工具，先找到和你有关的那一步。</p><a class="btn btn-lime" href="academy.html">去 AI 商学院 ↗</a></div><div class="member-edition-art"><small>AIRIS</small><b>AI</b><span>KNOWLEDGE<br>TALENT / GROWTH</span></div></section><div class="member-shortcuts">${destinations.slice(0,4).map(d=>`<a href="${d.href}"><small>${d.code}</small><strong>${d.label}</strong><span>${d.description}</span></a>`).join('')}</div><div class="work-columns"><section><h2 class="panel-title">先读这三篇<a href="#courses">全部入门阅读 →</a></h2><div class="member-reading">${guides.map((g,i)=>`<a href="#courses" data-guide="${g.id}"><span>0${i+1}</span><div><small>${g.type} / 入门指南</small><h3>${g.title}</h3><p>${g.description}</p></div><b>↗</b></a>`).join('')}</div></section><aside><h2 class="panel-title">我的学习记录</h2><article class="task-card"><span class="pill">本机记录</span><h3>从阅读到自己的判断</h3><p>已读 ${count} / 3 篇指南 · ${member.notes.length} 条笔记 · ${member.saved.length} 项收藏</p><div class="progress-track" role="progressbar" aria-label="入门阅读进度" aria-valuemin="0" aria-valuemax="3" aria-valuenow="${count}"><span style="width:${count/3*100}%"></span></div><div class="task-foot"><a href="#notes">写下我的想法 ↗</a><a href="#saved">打开收藏 ↗</a></div></article><div class="mentor-card"><span class="eyebrow">YOUR NEXT MOVE</span><h3>不知道从哪里开始？</h3><p>把你做的平台、当前问题说出来，让 AI 业务合伙人推荐浏览和学习入口。</p><a class="text-link small" style="margin-top:18px" href="partner.html">先聊聊 ↗</a></div></aside></div>`;}
function guideCards(){const selected=guides.filter(g=>(filter==='全部'||g.type===filter)&&`${g.title}${g.description}`.includes(query));return selected.length?`<div class="lab-course-grid">${selected.map(g=>`<article class="course-card"><div class="course-art ${g.type==='团队'?'dark':''}"><span class="small mono">AIRIS / 入门阅读</span><span class="caption">${g.label}</span><span class="big">↗</span></div><div class="course-meta"><span class="pill">${g.type}</span><h3>${g.title}</h3><p>${g.description}</p><button class="btn btn-primary" data-guide="${g.id}">${member.read.includes(g.id)?'再读一遍':'打开指南'} ↗</button><button class="guide-save" data-save="${g.id}" aria-pressed="${member.saved.includes(g.id)}">${member.saved.includes(g.id)?'已收藏 ✓':'收藏这篇'}</button></div></article>`).join('')}</div>`:'<div class="empty-state"><h3>暂时没有匹配的指南</h3><p>试试“工具”“团队”或“跨境”，也可以清除筛选。</p><button class="btn" data-action="reset-search">查看全部指南</button></div>';}
function renderCourses(){$('#workspace').innerHTML=`${heading('先把问题想清楚，再开始学习。','这三篇是入门阅读指南；培训视频、完整课程和讲师资料请进入 AI 商学院。','<a class="btn btn-primary" href="academy.html">浏览课程与视频 ↗</a>')}<div class="toolbar">${['全部','入门','团队','跨境'].map(f=>`<button class="filter-btn ${f===filter?'active':''}" data-filter="${f}" aria-pressed="${f===filter}">${f}</button>`).join('')}<input class="searchbox" aria-label="搜索入门指南" placeholder="搜索工具、团队或跨境" value="${escapeHTML(query)}"></div><div id="course-results">${guideCards()}</div>`;$('.searchbox').addEventListener('input',e=>{query=e.target.value;$('#course-results').innerHTML=guideCards();});}
function openGuide(id){const g=guides.find(g=>g.id===id);if(!g)return;openDialog(g.title,`<div class="lesson-content"><span class="pill">${g.type} · 入门阅读</span><p class="muted" style="margin-top:18px">${g.description}</p><ol>${g.steps.map(s=>`<li>${s}</li>`).join('')}</ol><div class="assignment"><b>留一个问题给自己</b><p style="margin:10px 0 0">${g.prompt}</p></div><div class="actions"><button class="btn btn-primary" data-read="${id}">${member.read.includes(id)?'已读 ✓':'标记已读'}</button><button class="btn" data-action="new-note">记下我的想法</button><a class="btn btn-soft" href="${g.href}">${g.link} ↗</a></div><p class="small muted" style="margin-top:20px">这是编辑整理的入门建议，阅读状态只保存在当前浏览器。</p></div>`);}
function renderNotes(){$('#workspace').innerHTML=`${heading('把想法写下来，下次接着想。','记录学到的方法、待确认的问题和想继续了解的主题。笔记只保存在当前浏览器。','<button class="btn btn-primary" data-action="new-note">＋ 写一条笔记</button>')}${member.notes.length?member.notes.map((n,i)=>`<article class="portfolio-card long-content"><span class="pill">${escapeHTML(n.topic)}</span><h3>${escapeHTML(n.title)}</h3><p class="note-text">${escapeHTML(n.body)}</p><button class="btn btn-soft" style="margin-top:18px" data-export="${i}">下载笔记 ↓</button></article>`).join(''):'<div class="empty-state"><h3>第一条笔记，从一个问题开始。</h3><p>今天听到什么观点、试了什么工具、还有什么没想明白，都可以记在这里。</p><button class="btn btn-primary" data-action="new-note">写下第一个问题</button></div>'}`;}
function newNote(){if(dialog.open)dialog.close();openDialog('写一条学习笔记',`<form id="note-form"><label class="field">笔记标题<input name="title" maxlength="80" required placeholder="例如：团队应该先学哪类 AI 工具？"></label><label class="field">关注方向<select name="topic"><option>工具与方法</option><option>课程学习</option><option>行业观察</option><option>团队成长</option></select></label><label class="field">我的想法<textarea name="body" maxlength="4000" required placeholder="写下学到的内容、自己的判断，或者还想继续问的问题。"></textarea><small>保存在当前浏览器，可下载为文本笔记。</small></label><p id="note-error" class="form-error" role="alert"></p><button class="btn btn-primary" type="submit">保存学习笔记</button></form>`);$('#note-form').addEventListener('submit',event=>{event.preventDefault();const data=new FormData(event.currentTarget);const title=String(data.get('title')).trim(),body=String(data.get('body')).trim();if(!title||!body){$('#note-error').textContent='请填写标题和想记录的内容。';return;}member.notes.unshift({title,body,topic:String(data.get('topic')),created:new Date().toISOString()});const persisted=save();dialog.close();location.hash='notes';render();if(persisted)toast('笔记已保存在本机。');});}
function renderResources(){$('#workspace').innerHTML=`${heading('需要什么，直接去对应的入口。','行业内容、工具、课程和交流各有独立栏目，方便你持续浏览。')}<div class="asset-grid">${destinations.map(d=>`<article class="asset-item"><div class="asset-icon">${d.code.split(' / ')[0]}</div><h3>${d.label}</h3><p>${d.description}</p><a href="${d.href}">进入栏目 ↗</a></article>`).join('')}</div><div class="state-note" style="margin-top:24px">培训视频与资料在 AI 商学院浏览；品牌标志与视觉规范可在 <a href="brand.html">品牌资产页</a> 下载。</div>`;}
let savedRender=0;
async function renderSaved(){
 const token=++savedRender,saved=guides.filter(g=>member.saved.includes(g.id)),articles=member.saved.filter(id=>typeof id==='string'&&!guides.some(g=>g.id===id));
 $('#workspace').innerHTML=`${heading('值得再看的，留在这里。','收藏的文章和入门指南，都留给下次的自己。收藏仅保存在当前浏览器。')}<div data-saved-guides>${saved.map(g=>`<article class="portfolio-card"><span class="pill">${g.type} · 入门指南</span><h3>${g.title}</h3><p>${g.description}</p><div class="actions" style="margin-top:18px"><button class="btn btn-primary" data-guide="${g.id}">继续阅读 ↗</button><button class="btn btn-soft" data-save="${g.id}">取消收藏</button></div></article>`).join('')}</div><div data-saved-articles>${articles.length?'<p role="status">正在打开收藏的文章…</p>':''}</div>${!saved.length&&!articles.length?'<div class="empty-state"><h3>收藏夹还是空的。</h3><p>从一篇和自己有关的内容开始，把有用的方法留住。</p><a class="btn btn-primary" href="intelligence.html">去看看行业情报 ↗</a></div>':''}`;
 if(!articles.length)return;
 const records=await Promise.all(articles.map(async id=>{try{const r=await window.AIRIS_CONTENT.fetch('/api/public/content/'+encodeURIComponent(id));if(!r.ok)return {id,unavailable:r.status===404};const item=await r.json();if(item.id!==id||item.status!=='published'||item.scheduled||(item.publish_at&&!(Date.parse(item.publish_at)<=Date.now())))return {id,unavailable:true};return {id,item}}catch{return {id,unavailable:false}}}));
 const target=$('[data-saved-articles]');if(token!==savedRender||!target)return;
 target.innerHTML=records.map(({id,item,unavailable})=>item?`<article class="portfolio-card long-content"><span class="pill">${escapeHTML(item.channel||'收藏内容')}</span><h3>${escapeHTML(item.title)}</h3><p>${escapeHTML(item.summary)}</p><div class="actions" style="margin-top:18px"><a class="btn btn-primary" href="content.html?id=${encodeURIComponent(id)}">继续阅读 ↗</a><button class="btn btn-soft" data-save="${escapeHTML(id)}">取消收藏</button></div></article>`:`<article class="portfolio-card"><h3>${unavailable?'这篇内容暂时未公开':'这篇收藏暂时没有加载出来'}</h3><p>${unavailable?'内容可能已下架，收藏记录仍为你保留。':'网络或内容服务暂时不可用，稍后可以再试。'}</p><div class="actions" style="margin-top:18px"><button class="btn btn-soft" data-action="reload-saved">重新加载</button><button class="btn btn-soft" data-save="${escapeHTML(id)}">取消收藏</button></div></article>`).join('');
}
window.addEventListener('storage',event=>{if(event.key!==stateKey)return;try{const stored=JSON.parse(event.newValue||'null');member=stored&&typeof stored==='object'?{read:Array.isArray(stored.read)?stored.read:[],saved:Array.isArray(stored.saved)?stored.saved.filter(id=>typeof id==='string'):[],notes:Array.isArray(stored.notes)?stored.notes.filter(n=>n&&typeof n.title==='string'&&typeof n.body==='string'):[]}:blankState();if(!dialog.open)render()}catch{}});

document.addEventListener('click',event=>{const el=event.target.closest('[data-guide],[data-read],[data-save],[data-filter],[data-export],[data-action]');if(!el)return;if(el.dataset.guide){event.preventDefault();openGuide(el.dataset.guide);return;}if(el.dataset.read){if(!member.read.includes(el.dataset.read))member.read.push(el.dataset.read);save();el.textContent='已读 ✓';render();return;}if(el.dataset.save){const id=el.dataset.save;member.saved=member.saved.includes(id)?member.saved.filter(x=>x!==id):[...member.saved,id];save();render();return;}if(el.dataset.filter){filter=el.dataset.filter;renderCourses();return;}if(el.dataset.export!==undefined){const note=member.notes[Number(el.dataset.export)];if(!note)return;const blob=new Blob([`# ${note.title}\n\n方向：${note.topic}\n\n${note.body}\n`],{type:'text/markdown;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='AIRIS-learning-note.md';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);return;}if(el.dataset.action==='reload-saved')renderSaved();if(el.dataset.action==='new-note')newNote();if(el.dataset.action==='reset-search'){query='';filter='全部';renderCourses();}});
window.addEventListener('hashchange',render);
render();
