const thread=document.querySelector('#chat-thread');const form=document.querySelector('#partner-form');const input=document.querySelector('#partner-input');
const answers=[['趋势','我先把这个问题放进「AI 电商情报中心」：你会看到平台变化、模型能力和业务场景的关系。你可以从栏目中的文章开始，找到和自己业务相关的问题。','进入情报中心 ↗','intelligence.html'],['工具','能力中心按常见业务场景整理了入门方法和可下载模板。工具是否适合，需要用你的真实任务验证。','浏览能力中心 ↗','toolkit.html'],['培训','我建议从「AI 商学院」的入门学习开始：先确定团队想提升的一个环节，再安排课程、作业与复盘。企业训练需由真人专家确认范围。','进入 AI 商学院 ↗','academy.html'],['诊断','这类需求适合进入企业合作路径：先了解业务梳理、团队训练和专家支持的合作方式。正式服务范围需由负责人确认。','规划企业路径 ↗','enterprise.html'],['default','我听到了。你可以先选择一个方向：看趋势、找工具、学课程、了解活动，或企业合作。','继续补充信息 ↗',''],['活动','活动栏目已整理外部平台活动与直播入口，你可以查看时间和原站详情。艾瑞斯自办活动会在确认后通过该栏目发布。','查看活动与直播 ↗','events.html']];
function addMessage(text,kind='user'){const row=document.createElement('div');row.className=`thread-message ${kind}`;const avatar=document.createElement('span');avatar.className='thread-avatar';avatar.textContent=kind==='ai'?'A':'YOU';const box=document.createElement('div');if(kind==='ai'){const label=document.createElement('small');label.textContent='艾瑞斯';box.append(label)}const p=document.createElement('p');p.textContent=text;box.append(p);row.append(avatar,box);thread.append(row);thread.scrollTop=thread.scrollHeight}
function addAnswer(msg,cta,href){const row=document.createElement('div');row.className='thread-message ai';const avatar=document.createElement('span');avatar.className='thread-avatar';avatar.textContent='A';const box=document.createElement('div');const label=document.createElement('small');label.textContent='艾瑞斯';const p=document.createElement('p');p.textContent=msg;const link=document.createElement('a');link.href=href;link.textContent=cta;box.append(label,p);if(href)box.append(link);row.append(avatar,box);thread.append(row);thread.scrollTop=thread.scrollHeight}
function pick(text){const matched=(window.AIRIS_PLATFORMS||[]).find(p=>({amazon:/亚马逊|amazon/i,tiktok:/tiktok|tik tok/i,independent:/独立站|shopify/i,crossborder:/跨境经营/,reception:/询盘|客服|接待/}[p.key])?.test(text));if(matched&&!/国际站|1688|一六八八|阿里巴巴内贸/.test(text))return [matched.key,'可以先从'+matched.label+'的内容频道开始。里面有完整方法文章、参考原文和工作清单，先挑一个你正遇到的问题。','阅读'+matched.label+'内容 ↗',matched.url];if(/国际站|alibaba\.com/i.test(text))return ['international','做国际站，可以先把海外买家、产品表达和询盘沟通这几件事理顺。专区整理了可直接阅读的方法和四节沟通文字课，先挑与你眼前问题最贴近的内容。','进入国际站专区 ↗','international.html'];if(/1688|一六八八|阿里巴巴内贸/.test(text))return ['1688','做 1688，可以先从产品表达、询盘回复和选品采购里挑一件事。内容分类里有完整方法文章和三节文字课，先找到与你眼前问题最贴近的一份。','查看 1688 经营内容 ↗','channel.html?platform=1688'];if(/活动|论坛|工作坊|嘉宾/.test(text))return answers[5];if(/趋势|洞察|变化|市场/.test(text))return answers[0];if(/工具|效率|提效|自动化/.test(text))return answers[1];if(/诊断|合作|企业|咨询|接待|客户/.test(text))return answers[3];if(/培训|课程|学习|团队/.test(text))return answers[2];return answers[4]}
function respond(text){const [_,msg,cta,href]=pick(text);setTimeout(()=>addAnswer(msg,cta,href),360)}
document.querySelectorAll('[data-ask]').forEach(btn=>btn.addEventListener('click',()=>{const text=btn.dataset.ask;addMessage(text);respond(text)}));
form?.addEventListener('submit',e=>{e.preventDefault();const text=input.value.trim();if(!text)return;addMessage(text);input.value='';respond(text)});
const preset=sessionStorage.getItem('airisPartnerPrompt');if(preset){sessionStorage.removeItem('airisPartnerPrompt');addMessage(preset);respond(preset)}

if(new URLSearchParams(location.search).get('topic')==='event'){addAnswer(answers[5][1],answers[5][2],answers[5][3]);}

const intent=new URLSearchParams(location.search).get('intent');
const intentPrompt={international:'我做阿里国际站，想用 AI 改善产品表达和询盘沟通',wholesale:'我做 1688，想看看 AI 怎么帮到店铺经营',training:'我想给团队做 AI 培训',tools:'我做跨境，想找适合的工具',business:'我想了解 AI 自动接待和企业合作',cooperation:'我是一名专家，想了解内容与课程合作'};
if(intentPrompt[intent]){addMessage(intentPrompt[intent]);respond(intentPrompt[intent]);}
