(function(){'use strict';
const $=(s,p=document)=>p.querySelector(s), $$=(s,p=document)=>[...p.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const guides=window.AIRIS_GUIDES||[], catalog=$('[data-catalog]');
const routeType=catalog?.dataset.catalog, fixedCategory=catalog?.dataset.fixedCategory||'';
const allowedTypes=$('#content-format')?$$('#content-format option').map(option=>option.value):['article','video','report','page'];
const query=new URLSearchParams(location.search);let state={type:routeType==='collection'?'':routeType==='article'&&allowedTypes.includes(query.get('type'))?query.get('type'):routeType,category:fixedCategory||query.get('category')||'',q:query.get('q')||'',page:Math.max(1,Number(query.get('page'))||1),pageSize:6}, sequence=0;
const mediaURL=id=>window.AIRIS_CONTENT.mediaURL(id);
const date=s=>s?new Date(s).toLocaleDateString('zh-CN'):'';
function pages(total,page,size){const n=Math.ceil(total/size);if(n<2)return '';const visible=[...new Set([1,page-1,page,page+1,n].filter(x=>x>0&&x<=n))].sort((a,b)=>a-b);return visible.map((x,i)=>`${i&&x>visible[i-1]+1?'<span>…</span>':''}<button type="button" class="page-button${x===page?' active':''}" data-page="${x}" ${x===page?'aria-current="page"':''}>${x}</button>`).join('')}
function card(item,i){if(routeType==='collection'){const references=(String(item.body||'').match(/\[[^\]\n]+\]\(https?:\/\/[^\s)]+\)/g)||[]).length;const minutes=Math.max(1,Math.ceil(String(item.body||'').replace(/https?:\/\/\S+/g,'').length/350));return `<a class="collection-article" href="content.html?id=${encodeURIComponent(item.id)}"><span class="collection-kind">${item.type==='course'?'文字课程':references?'资料导读与实操':({article:'原创方法',video:'视频内容',report:'参考资料',page:'专题内容'}[item.type]||'经营内容')}</span><h2>${esc(item.title)}</h2><p>${esc(item.summary)}</p><div class="collection-meta"><span>${esc(item.author||'艾瑞斯编辑部')}</span><span>${item.type==='course'?`${(item.chapters||[]).length} 个小节`:`约 ${minutes} 分钟`}</span>${references?`<span>${references} 处参考原文</span>`:''}<span>阅读全文 ↗</span></div></a>`}return `<a class="catalog-card" href="content.html?id=${encodeURIComponent(item.id)}"><div class="catalog-card-art art-${i%3}">${item.cover_media_id?`<img src="${mediaURL(item.cover_media_id)}" alt="" loading="lazy">`:`<span>${esc(item.channel||'艾瑞斯精选')}</span><strong>${item.type==='course'?`${(item.chapters||[]).length} 个小节`:({article:'读一读',video:'看一看',event:'去交流',report:'好好收藏',page:'了解更多'}[item.type]||'继续了解')}</strong>`}</div><div class="catalog-card-body"><small>${esc(item.channel||'方法与观察')}</small><h2>${esc(item.title)}</h2><p>${esc(item.summary)}</p><div class="catalog-card-meta"><span>${esc(item.author||'艾瑞斯')}</span><span>${item.type==='course'?`${(item.chapters||[]).length} 个小节`:date(item.published_at||item.publish_at)||'方法指南'} ↗</span></div></div></a>`}
async function load(page=state.page){const token=++sequence;state.page=page;const grid=$('[data-catalog-list]'),count=$('[data-result-count]'),pager=$('[data-pagination]');grid.setAttribute('aria-busy','true');grid.innerHTML='<div class="loading-state">正在读取已发布内容…</div>';pager.innerHTML='';const p=new URLSearchParams({page:String(page),page_size:String(state.pageSize)});if(state.type)p.set('type',state.type);if(state.category)p.set('category',state.category);if(state.q)p.set('q',state.q);let data,offline=location.protocol==='file:';
try{if(offline)throw new Error('file preview');const res=await window.AIRIS_CONTENT.fetch('/api/public/content?'+p);if(!res.ok)throw new Error('HTTP '+res.status);data=await res.json()}catch(error){if(!offline){if(token!==sequence)return;grid.innerHTML=`<div class="error-state"><div><h2>内容暂时没有加载出来</h2><p>请稍后重试。</p><button class="button primary" data-retry>重新加载</button></div></div>`;count.textContent='连接暂时中断';grid.removeAttribute('aria-busy');return}const items=guides.filter(x=>!state.type||x.type===state.type).filter(x=>(!state.category||x.channel===state.category)&&(!state.q||`${x.title} ${x.summary} ${x.channel}`.includes(state.q)));data={items:items.slice((page-1)*state.pageSize,page*state.pageSize),total:items.length}}
if(token!==sequence)return;const pagesCount=Math.ceil(data.total/state.pageSize);if(page>Math.max(1,pagesCount)){load(Math.max(1,pagesCount));return}grid.removeAttribute('aria-busy');grid.innerHTML=data.items.length?data.items.map(card).join(''):`<div class="empty-state"><div><h2>${state.q||state.category?'没有找到匹配内容':state.type==='course'?'课程发布后，会在这里与你见面。':state.type==='event'?'下一场交流，正在筹备。':'新的内容正在准备。'}</h2><p>${state.q||state.category?'换一个关键词，或查看全部。':state.type==='course'?'先读一份指南，或找到适合自己的学习方向。':state.type==='event'?'活动日期、嘉宾和参与方式确认后在这里发布。':'内容发布后会在这里更新。先去能力中心看看，或找到你的下一步。'}</p>${state.q||state.category?'<button class="button primary" data-reset>查看全部</button>':'<a class="button primary" href="partner.html">帮我找下一步 ↗</a>'}</div></div>`;
count.textContent=`${data.total} ${state.type==='course'?'门课程':state.type==='event'?'项活动':'条内容'}${offline?' · 本地预览':''}`;pager.innerHTML=pages(data.total,page,state.pageSize);const u=new URL(location.href);for(const key of ['q','category','page','type']){if(state[key]&&state[key]!==1)u.searchParams.set(key,String(state[key]));else u.searchParams.delete(key)}history.replaceState(null,'',u);}
function initCatalog(){if(!catalog)return;const format=$('#content-format');if(format){format.value=state.type;format.addEventListener('change',()=>{state.type=format.value;load(1)})}$('#catalog-query').value=state.q;$$('[data-category]').forEach(b=>{const selected=b.dataset.category===state.category;b.classList.toggle('active',selected);b.setAttribute('aria-pressed',String(selected));b.addEventListener('click',()=>{state.category=fixedCategory||b.dataset.category;$$('[data-category]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',String(x===b))});load(1)})});$('.catalog-search')?.addEventListener('submit',e=>{e.preventDefault();state.q=$('#catalog-query').value.trim();load(1)});catalog.addEventListener('click',e=>{const p=e.target.closest('[data-page]');if(p){load(Number(p.dataset.page));$('.catalog-tools').scrollIntoView({behavior:'smooth',block:'start'})}if(e.target.closest('[data-retry]'))load();if(e.target.closest('[data-reset]')){if(fixedCategory&&!state.q){state.type=routeType==='collection'?'':'article';if(format)format.value=state.type}state.q='';$('#catalog-query').value='';$$('[data-category]').find(b=>b.dataset.category===fixedCategory)?.click()}});load()}
async function initHome(){const target=$('[data-home-content]');if(!target)return;let items=guides.filter(x=>x.type==='article').slice(0,4);if(location.protocol!=='file:'){try{const r=await window.AIRIS_CONTENT.fetch('/api/public/content?type=article&page_size=4');if(!r.ok)throw new Error();items=(await r.json()).items}catch{return}}if(!items.length){target.innerHTML='<div class="empty-state">编辑推荐正在准备，先去能力中心看看。</div>';return}const lead=items[0];target.innerHTML=`<a class="feature-story" href="content.html?id=${encodeURIComponent(lead.id)}"><div class="story-art"><span>YOUR<br>NEXT<br>MOVE.</span><i>AI × COMMERCE</i></div><div class="story-copy"><small>${esc(lead.channel)} · 方法指南</small><h3>${esc(lead.title)}</h3><p>${esc(lead.summary)}</p><b>阅读指南 ↗</b></div></a><div class="story-list">${items.slice(1).map(x=>`<a href="content.html?id=${encodeURIComponent(x.id)}"><small>${esc(x.channel)}</small><h3>${esc(x.title)}</h3><span>阅读内容 →</span></a>`).join('')}</div>`}
// 仅允许明确的 HTTP(S) Markdown 来源链接；其他输入继续按纯文本转义。
function inlineText(text){let html='',cursor=0;const pattern=/\[([^\]\n]+)\]\((https?:\/\/[^\s)]+)\)/g;for(const match of String(text).matchAll(pattern)){html+=esc(text.slice(cursor,match.index));let url;try{url=new URL(match[2])}catch{}html+=url&&['https:','http:'].includes(url.protocol)?`<a class="source-reference" href="${esc(url.href)}" target="_blank" rel="noopener noreferrer">${esc(match[1])}<span aria-hidden="true"> ↗</span></a>`:esc(match[0]);cursor=match.index+match[0].length}return html+esc(String(text).slice(cursor))}
// CMS 正文按纯文本呈现，只拆分阅读段落，不接受 HTML。
function readableParagraphs(text,lead=false){
 const lines=String(text||'').split(/\n+/).filter(x=>x.trim());
 return lines.flatMap(line=>{if(/\[[^\]\n]+\]\(https?:\/\/[^\s)]+\)/.test(line))return [line];const sentences=line.match(/[^。！？!?]+[。！？!?]?[”’」』"]?|[。！？!?]/g)||[line];const chunks=[];let current='';for(const sentence of sentences){if(current.length>=150){chunks.push(current);current=''}current+=sentence}if(current)chunks.push(current);return chunks}).map((part,i)=>`<p${lead&&i===0?' class="article-lead"':''}>${inlineText(part)}</p>`).join('');
}
async function initDetail(){
 const host=$('[data-content-detail]');if(!host)return;
 const id=query.get('id');let item;
 if(location.protocol==='file:')item=guides.find(x=>x.id===id);
 else if(id){try{const r=await window.AIRIS_CONTENT.fetch('/api/public/content/'+encodeURIComponent(id));if(!r.ok)throw new Error('HTTP '+r.status);item=await r.json()}catch{}}
 host.removeAttribute('aria-busy');
 if(!item){host.innerHTML='<div class="empty-state"><div><h1>这篇内容暂时无法打开</h1><p>它可能尚未公开、已下架，或内容服务暂时不可用。</p><a class="button primary" href="intelligence.html">返回情报中心</a></div></div>';return}
 document.title=item.title+' · 艾瑞斯 AIRIS';
 const channel=(window.AIRIS_PLATFORMS||[]).find(p=>p.category===item.channel);
 const type=channel?channel.url:item.type==='course'?'academy.html':item.type==='event'?'events.html':'intelligence.html';
 const sections=String(item.body||'').split(/\n{2,}/).filter(x=>x.trim());
 const sectionTitle=(p,i)=>i===0?'从这里读起':p.includes('\n')&&p.split('\n')[0].length<=70?p.split('\n')[0]:`接着读 · 第 ${i+1} 段`;
 const body=sections.map((p,i)=>{const line=p.indexOf('\n'),hasHeading=i>0&&line>0&&line<=70;return `<section id="part-${i}">${hasHeading?`<h2>${esc(p.slice(0,line))}</h2>${readableParagraphs(p.slice(line+1))}`:readableParagraphs(p,i===0)}</section>`}).join('');
 const chapters=(item.chapters||[]).map((ch,i)=>`<section class="lesson" id="lesson-${i}"><small>第 ${i+1} 小节</small><h2>${esc(ch.title)}</h2><p>${esc(ch.description)}</p>${ch.video_media_id?`<video controls preload="metadata" playsinline src="${mediaURL(ch.video_media_id)}"></video><p class="video-help">如当前浏览器不支持此视频格式，可下载后播放。<a href="${mediaURL(ch.video_media_id)}?download=1" download>下载视频 ↓</a></p>`:''}${(ch.material_media_ids||[]).map((m,j)=>`<a class="material-download" href="${mediaURL(m)}?download=1" download>本小节资料${(ch.material_media_ids||[]).length>1?` ${j+1}`:''}<span>下载 ↓</span></a>`).join('')}</section>`).join('');
 host.innerHTML=`<a class="detail-back" href="${type}">← 返回${channel?channel.label+'内容':item.type==='course'?'AI 商学院':item.type==='event'?'活动与直播':'行业情报'}</a><header class="detail-header"><p class="overline blue">${esc(item.channel||'艾瑞斯精选')}</p><h1>${esc(item.title)}</h1><p>${esc(item.summary)}</p><div class="detail-byline"><span>${esc(item.author||'艾瑞斯')} · ${date(item.published_at||item.publish_at)||'方法指南'}</span><span data-reading-time></span></div></header><div class="detail-layout"><article class="detail-body"><div class="reading-text" data-reading-text>${body}${chapters}</div><div data-reading-end></div></article><aside class="detail-side"><b>按自己的节奏读</b><nav aria-label="阅读目录">${sections.map((p,i)=>`<a href="#part-${i}">${esc(sectionTitle(p,i))}</a>`).join('')}${(item.chapters||[]).map((ch,i)=>`<a href="#lesson-${i}">${esc(ch.title)}</a>`).join('')}</nav><div class="detail-prompt"><h3>第一次来，不必一下学完。</h3><p>先找到一个与你有关的问题，再慢慢往下看。</p><a href="lab.html#courses">从入门阅读开始</a></div></aside></div>`;
 window.AIRIS_READING?.mount(item,host);
}

initCatalog();initHome();initDetail();
})();
